# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-04 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quotas', models.BooleanField(default=False, help_text='cupos solicitados')),
            ],
            options={
                'verbose_name': 'viaje',
                'verbose_name_plural': 'viajes',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateTimeField(verbose_name='fecha de viaje')),
                ('quotas', models.PositiveSmallIntegerField(verbose_name='cupos')),
                ('city_from', models.PositiveSmallIntegerField(choices=[(1, 'Armenia'), (3, 'Barranquilla'), (2, 'Barrancabermeja'), (4, 'Bogotá'), (5, 'Bucaramanga'), (6, 'Caldas (Antioquia)'), (7, 'Cali'), (8, 'Cartagena'), (9, 'Cúcuta'), (10, 'Florencia - Caqueta'), (11, 'Manizales'), (12, 'Medellín'), (13, 'Montería'), (15, 'Pamplona'), (16, 'Pasto'), (17, 'Pereira'), (18, 'Popayán'), (19, 'Soacha'), (20, 'Sogamoso'), (21, 'Tunja'), (14, 'Otra'), (22, 'Fuera del país')], max_length=50, verbose_name='ciudad de origen')),
                ('city_to', models.PositiveSmallIntegerField(choices=[(1, 'Armenia'), (3, 'Barranquilla'), (2, 'Barrancabermeja'), (4, 'Bogotá'), (5, 'Bucaramanga'), (6, 'Caldas (Antioquia)'), (7, 'Cali'), (8, 'Cartagena'), (9, 'Cúcuta'), (10, 'Florencia - Caqueta'), (11, 'Manizales'), (12, 'Medellín'), (13, 'Montería'), (15, 'Pamplona'), (16, 'Pasto'), (17, 'Pereira'), (18, 'Popayán'), (19, 'Soacha'), (20, 'Sogamoso'), (21, 'Tunja'), (14, 'Otra'), (22, 'Fuera del país')], max_length=50, verbose_name='ciudad de destino')),
            ],
            options={
                'verbose_name': 'viaje',
                'verbose_name_plural': 'viajes',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=128, verbose_name='nombre')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo electrónico')),
                ('is_driver', models.BooleanField(default=False, help_text='Indica si el usuario es conductor')),
            ],
            options={
                'verbose_name': 'viaje',
                'verbose_name_plural': 'viajes',
                'ordering': ('-id',),
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='conductor'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Trip', verbose_name='viaje'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User', verbose_name='usuario'),
        ),
    ]
