# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-04 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ('-id',), 'verbose_name': 'reservacion', 'verbose_name_plural': 'reservaciones'},
        ),
        migrations.AlterField(
            model_name='reservation',
            name='requested_quotas',
            field=models.PositiveSmallIntegerField(default=False, help_text='cupos solicitados'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='city_from',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Armenia'), (3, 'Barranquilla'), (2, 'Barrancabermeja'), (4, 'Bogotá'), (5, 'Bucaramanga'), (6, 'Caldas (Antioquia)'), (7, 'Cali'), (8, 'Cartagena'), (9, 'Cúcuta'), (10, 'Florencia - Caqueta'), (11, 'Manizales'), (12, 'Medellín'), (13, 'Montería'), (15, 'Pamplona'), (16, 'Pasto'), (17, 'Pereira'), (18, 'Popayán'), (19, 'Soacha'), (20, 'Sogamoso'), (21, 'Tunja'), (14, 'Otra'), (22, 'Fuera del país')], verbose_name='ciudad de origen'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='city_to',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Armenia'), (3, 'Barranquilla'), (2, 'Barrancabermeja'), (4, 'Bogotá'), (5, 'Bucaramanga'), (6, 'Caldas (Antioquia)'), (7, 'Cali'), (8, 'Cartagena'), (9, 'Cúcuta'), (10, 'Florencia - Caqueta'), (11, 'Manizales'), (12, 'Medellín'), (13, 'Montería'), (15, 'Pamplona'), (16, 'Pasto'), (17, 'Pereira'), (18, 'Popayán'), (19, 'Soacha'), (20, 'Sogamoso'), (21, 'Tunja'), (14, 'Otra'), (22, 'Fuera del país')], verbose_name='ciudad de destino'),
        ),
    ]
