# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-04 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181104_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_driver', models.BooleanField(default=False, help_text='Indica si el usuario es conductor')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='requested_quotas',
            field=models.PositiveSmallIntegerField(help_text='cupos solicitados'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Client', verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Client', verbose_name='conductor'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
