# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-04 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181104_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('-id',), 'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='1', max_length=254, unique=True, verbose_name='correo electrónico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(default='1', max_length=128, verbose_name='nombre'),
            preserve_default=False,
        ),
    ]
