# Generated by Django 2.1.1 on 2018-11-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20181115_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='price',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='precio'),
        ),
    ]
